### ISSUE TITLE
knitr dependency?

### ISSUE THREAD

**Issue by kslays** [r-lib/rprojroot#39]
I believe the package should import knitr.

I installed rprojroot on a new machine, and tried to run thisfile(), but had the following error message.
> thisfile()
Loading required namespace: knitr
Failed with error:  ‘there is no package called ‘knitr’’

I installed knitr manually and then thisfile() worked.

**Comment by owenjonesuob** [comment]
It looks like this is by design: **knitr** is listed in the "Suggests" section of the DESCRIPTION file, so won't usually be installed as a dependency when **rprojroot** is installed.

Most likely this is because **knitr** is only needed for one very specific use case: using `rprojroot::thisfile()` to identify the path of a document which is actively being knitted by **knitr**. So the author has decided that rather than forcing _everyone_ who installs **rprojroot** to also install **knitr**, it is left as an optional extra.

If **knitr** isn't present, the error message provides a strong hint that all we need to do is install it ourselves, exactly as you did!

**Comment by krlmlr** [comment]
Thanks. `thisfile()` and friends have moved to {whereami}, I will add a deprecation message.
